#!/usr/bin/env zsh

# gcloud 実行ファイルがあるディレクトリをパスに追加
export PATH="$PATH:/usr/local/bin:/usr/bin:/bin:$HOME/.local/opt/google-cloud-sdk/bin"
mkdir -p ~/{.cache/ytpl-list/{view,index},.config/ytpl-list,.local/share/ytpl-list}
touch ~/.config/ytpl-list/config
source ~/.config/ytpl-list/config # apiKey
prefix="https://youtube.googleapis.com/youtube/v3"
page=''
gcloud auth application-default print-access-token |
sponge |
awk '{print "Authorization: Bearer "$1}' |
read field1 # doesn't work in bash
field2="Accept: application/json"

_sync(){
  endpoint="$prefix/playlists"
  part="snippet%2CcontentDetails%2Cid%2Cstatus%2Clocalizations"
  timestamp=$(date +"%Y%m%d-%H%M%S")
  while true
  do
  # maxResults は仕様上最大50
  echo $endpoint'?part='$part'&maxResults=50&mine=true&pageToken='$page |
  xargs curl -sL -H $field1 -H $field2 --compressed |
  tee -a ~/.cache/ytpl-list/index/$timestamp.json |
  sponge |
  jq -r '.nextPageToken // empty' |
  read page
  test -z "$page" && exit 1
  done;
}
_list(){

}
_total(){

}
_get(){
  endpoint="$prefix/playlistItems"
  part="contentDetails%2Cid%2Csnippet%2Cstatus"
  timestamp=$(date +"%Y%m%d-%H%M%S")
  while true
  do
  echo $endpoint'?part='$part'&maxResults=50&playlistId='$id'&pageToken='$page'$key='$apiKey |
  xargs curl -sL -H $field1 -H $field2 --compressed |
  tee -a ~/.local/share/ytpl-list/$timestamp.json |
  sponge |
  jq -r '.nextPageToken // empty' |
  read page
  test -z "$page" && exit 1
  done;

}
_view(){

}

case "$1" in
  "sync" ) _sync ;;
  "list" ) _list ;;
  "total" ) _total ;;
  "get" ) _get ;;
  "view" ) _view ;;
  * ) echo "Argument Error: sync, list, total, get, or view." ;;
esac

# jq -r '.items.[].id' temp.json
# jq -r '.items.[].snippet.title' temp.json
# jq -r '.pageInfo.totalResults' temp.json | head -n 1
